// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekdEEMn42OJzxTTBAGUAEFTDDVdU_SbA',
    appId: '1:699692984203:web:2d2241491eb0c16c15b18e',
    messagingSenderId: '699692984203',
    projectId: 'landregistry-15941',
    authDomain: 'landregistry-15941.firebaseapp.com',
    storageBucket: 'landregistry-15941.appspot.com',
    measurementId: 'G-W8GMKR3MSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGyfvqq0iOV-wsg0xkxzPXXvirJxInMM',
    appId: '1:699692984203:android:c3e01bd3f04a211d15b18e',
    messagingSenderId: '699692984203',
    projectId: 'landregistry-15941',
    storageBucket: 'landregistry-15941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJW60r7xh8sUlEiS-hGgaeiFybH2QWa0I',
    appId: '1:699692984203:ios:7b347eb500994f7115b18e',
    messagingSenderId: '699692984203',
    projectId: 'landregistry-15941',
    storageBucket: 'landregistry-15941.appspot.com',
    iosBundleId: 'com.example.landsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJW60r7xh8sUlEiS-hGgaeiFybH2QWa0I',
    appId: '1:699692984203:ios:7b347eb500994f7115b18e',
    messagingSenderId: '699692984203',
    projectId: 'landregistry-15941',
    storageBucket: 'landregistry-15941.appspot.com',
    iosBundleId: 'com.example.landsystem',
  );
}
